import AppKit
import Foundation
import Testing
@testable import PladderSystem

/// Every test writes to a private named pasteboard, never `.general`: the
/// developer dictates with a running Pladder while these run.
@Suite struct PasteboardOutputTests {
    private static func namedPasteboard() -> NSPasteboard {
        NSPasteboard(name: .init("de.dinooo13.pladder.tests.\(UUID().uuidString)"))
    }

    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    @Test func transcriptCarriesTransientMarkers() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        _ = PasteboardOutput.Snapshot.write("hello", to: pasteboard)

        #expect(pasteboard.string(forType: .string) == "hello")
        let item = try #require(pasteboard.pasteboardItems?.first)
        let types = Set(item.types)
        #expect(types.isSuperset(of: [Self.transient, Self.concealed, Self.autoGenerated]))
        #expect(pasteboard.string(forType: Self.source) == Bundle.main.bundleIdentifier ?? "de.dinooo13.pladder")
    }

    @Test func writeReturnsTheNewChangeCount() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let before = pasteboard.changeCount
        let returned = PasteboardOutput.Snapshot.write("hello", to: pasteboard)

        #expect(returned == pasteboard.changeCount)
        #expect(returned > before)
    }

    @Test func restoreRoundTripsAfterAMarkedWrite() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let original = NSPasteboardItem()
        original.setData(Data("user text".utf8), forType: .string)
        original.setData(Data("<html>user text</html>".utf8), forType: .html)
        pasteboard.clearContents()
        pasteboard.writeObjects([original])

        let snapshot = PasteboardOutput.Snapshot.capture(from: pasteboard)
        let ourChangeCount = PasteboardOutput.Snapshot.write("transcript", to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "transcript")

        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "user text")
        #expect(pasteboard.string(forType: .html) == "<html>user text</html>")
        let types = Set(try #require(pasteboard.pasteboardItems?.first).types)
        #expect(types.isDisjoint(with: [Self.transient, Self.concealed, Self.autoGenerated, Self.source]))
    }

    @Test func restoreLeavesAPasteboardSomebodyElseWroteAlone() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        pasteboard.clearContents()
        pasteboard.setString("user text", forType: .string)
        let snapshot = PasteboardOutput.Snapshot.capture(from: pasteboard)
        let ourChangeCount = PasteboardOutput.Snapshot.write("transcript", to: pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("something the user copied", forType: .string)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "something the user copied")
    }

    // MARK: The transcript as a promise

    /// Records every read the promise reports.
    private final class Reads: @unchecked Sendable {
        private let lock = NSLock()
        private var _count = 0
        var count: Int { lock.withLock { _count } }
        func record() { lock.withLock { _count += 1 } }
    }

    /// Main actor: AppKit serves an in-process promise read synchronously and
    /// warns when that happens off the main thread.
    @MainActor @Test func publishedTranscriptIsServedMarkedAndReportsTheRead() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        let reads = Reads()
        let promise = TranscriptPromise("hello") { _, _ in reads.record() }

        let changeCount = PasteboardOutput.Snapshot.publish(promise, to: pasteboard)

        #expect(changeCount == pasteboard.changeCount)
        #expect(reads.count == 0)
        let types = Set(try #require(pasteboard.pasteboardItems?.first).types)
        #expect(types.isSuperset(of: [.string, Self.transient, Self.concealed, Self.autoGenerated, Self.source]))
        #expect(pasteboard.string(forType: .string) == "hello")
        #expect(reads.count == 1)
    }

    @MainActor @Test func restoreRoundTripsAfterAPublishedTranscript() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("user text", forType: .string)
        let snapshot = PasteboardOutput.Snapshot.capture(from: pasteboard)

        let promise = TranscriptPromise("transcript") { _, _ in }
        let ourChangeCount = PasteboardOutput.Snapshot.publish(promise, to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "transcript")
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "user text")
    }

    // MARK: When the old clipboard comes back

    private static let posted = ContinuousClock.now
    private static func due(read: Duration?) -> Duration {
        PasteboardOutput.restoreDue(
            posted: posted, lastRead: read.map { posted + $0 },
            floor: .milliseconds(400), settle: .milliseconds(200), cap: .seconds(8)) - posted
    }

    @Test func nothingReadWaitsForTheCap() {
        #expect(Self.due(read: nil) == .seconds(8))
    }

    @Test func aPromptReadKeepsTheOldDelay() {
        #expect(Self.due(read: .milliseconds(12)) == .milliseconds(400))
    }

    @Test func aLateReadIsWaitedFor() {
        // A busy page reads a second after Cmd+V; the old 400 ms delay alone
        // had already put the user's clipboard back by then.
        #expect(Self.due(read: .milliseconds(1_006)) == .milliseconds(1_206))
    }

    @Test func aReadNearTheCapStillEndsAtTheCap() {
        #expect(Self.due(read: .milliseconds(7_900)) == .seconds(8))
    }

    @Test func aReadBeforeCmdVKeepsTheOldDelay() {
        #expect(Self.due(read: .milliseconds(-5)) == .milliseconds(400))
    }
}
