import AppKit
import Foundation
import Testing
@testable import PladderSystem

/// Every test writes to a private named pasteboard, never `.general`: the
/// developer dictates with a running Pladder while these run.
@Suite struct PasteboardOutputTests {
    private static func namedPasteboard() -> NSPasteboard {
        NSPasteboard(name: .init("de.dinooo13.pladder.tests.\(UUID().uuidString)"))
    }

    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    @Test func transcriptCarriesTransientMarkers() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        _ = PasteboardOutput.Snapshot.write("hello", to: pasteboard)

        #expect(pasteboard.string(forType: .string) == "hello")
        let item = try #require(pasteboard.pasteboardItems?.first)
        let types = Set(item.types)
        #expect(types.isSuperset(of: [Self.transient, Self.concealed, Self.autoGenerated]))
        #expect(pasteboard.string(forType: Self.source) == Bundle.main.bundleIdentifier ?? "de.dinooo13.pladder")
    }

    @Test func writeReturnsTheNewChangeCount() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let before = pasteboard.changeCount
        let returned = PasteboardOutput.Snapshot.write("hello", to: pasteboard)

        #expect(returned == pasteboard.changeCount)
        #expect(returned > before)
    }

    @Test func restoreRoundTripsAfterAMarkedWrite() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let original = NSPasteboardItem()
        original.setData(Data("user text".utf8), forType: .string)
        original.setData(Data("<html>user text</html>".utf8), forType: .html)
        pasteboard.clearContents()
        pasteboard.writeObjects([original])

        let snapshot = PasteboardOutput.Snapshot.capture(from: pasteboard)
        let ourChangeCount = PasteboardOutput.Snapshot.write("transcript", to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "transcript")

        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "user text")
        #expect(pasteboard.string(forType: .html) == "<html>user text</html>")
        let types = Set(try #require(pasteboard.pasteboardItems?.first).types)
        #expect(types.isDisjoint(with: [Self.transient, Self.concealed, Self.autoGenerated, Self.source]))
    }

    @Test func restoreLeavesAPasteboardSomebodyElseWroteAlone() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        pasteboard.clearContents()
        pasteboard.setString("user text", forType: .string)
        let snapshot = PasteboardOutput.Snapshot.capture(from: pasteboard)
        let ourChangeCount = PasteboardOutput.Snapshot.write("transcript", to: pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("something the user copied", forType: .string)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "something the user copied")
    }
}
