import AppKit
import Foundation
import PladderTestSupport
import Testing
@testable import PladderSystem

/// Every test writes to a private named pasteboard, never `.general`: the
/// developer dictates with a running Pladder while these run.
@Suite struct PasteboardOutputTests {
    private static func namedPasteboard() -> NSPasteboard {
        NSPasteboard(name: .init("de.dinooo13.pladder.tests.\(UUID().uuidString)"))
    }

    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    @Test func transcriptCarriesTransientMarkers() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        _ = ClipboardSnapshot.write("hello", to: pasteboard)

        #expect(pasteboard.string(forType: .string) == "hello")
        let item = try #require(pasteboard.pasteboardItems?.first)
        let types = Set(item.types)
        #expect(types.isSuperset(of: [Self.transient, Self.concealed, Self.autoGenerated]))
        #expect(pasteboard.string(forType: Self.source) == Bundle.main.bundleIdentifier ?? "de.dinooo13.pladder")
    }

    @Test func writeReturnsTheNewChangeCount() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let before = pasteboard.changeCount
        let returned = ClipboardSnapshot.write("hello", to: pasteboard)

        #expect(returned == pasteboard.changeCount)
        #expect(returned > before)
    }

    @Test func restoreRoundTripsAfterAMarkedWrite() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        let original = NSPasteboardItem()
        original.setData(Data("user text".utf8), forType: .string)
        original.setData(Data("<html>user text</html>".utf8), forType: .html)
        pasteboard.clearContents()
        pasteboard.writeObjects([original])

        let snapshot = ClipboardSnapshot.capture(from: pasteboard)
        let ourChangeCount = ClipboardSnapshot.write("transcript", to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "transcript")

        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "user text")
        #expect(pasteboard.string(forType: .html) == "<html>user text</html>")
        let types = Set(try #require(pasteboard.pasteboardItems?.first).types)
        #expect(types.isDisjoint(with: [Self.transient, Self.concealed, Self.autoGenerated, Self.source]))
    }

    @Test func restoreLeavesAPasteboardSomebodyElseWroteAlone() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }

        pasteboard.clearContents()
        pasteboard.setString("user text", forType: .string)
        let snapshot = ClipboardSnapshot.capture(from: pasteboard)
        let ourChangeCount = ClipboardSnapshot.write("transcript", to: pasteboard)

        pasteboard.clearContents()
        pasteboard.setString("something the user copied", forType: .string)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "something the user copied")
    }

    // MARK: Items too large to keep

    @Test func aSnapshotOfOnlyOversizedItemsLeavesTheTranscript() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("a copied video, say", forType: .string)

        let snapshot = ClipboardSnapshot.capture(from: pasteboard, maximumItemBytes: 4)
        #expect(snapshot.items.isEmpty)
        #expect(snapshot.droppedItems == 1)
        let ourChangeCount = ClipboardSnapshot.write("transcript", to: pasteboard)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        // Not wiped: the transcript is the lesser loss.
        #expect(pasteboard.string(forType: .string) == "transcript")
    }

    @Test func anOversizedItemIsLeftOutAndTheRestRestored() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        let small = NSPasteboardItem()
        small.setString("small", forType: .string)
        let large = NSPasteboardItem()
        large.setString("this one is far too large", forType: .string)
        pasteboard.clearContents()
        pasteboard.writeObjects([small, large])

        let snapshot = ClipboardSnapshot.capture(from: pasteboard, maximumItemBytes: 8)
        #expect(snapshot.items.count == 1)
        #expect(snapshot.droppedItems == 1)
        let ourChangeCount = ClipboardSnapshot.write("transcript", to: pasteboard)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.pasteboardItems?.count == 1)
        #expect(pasteboard.string(forType: .string) == "small")
    }

    @Test func anEmptyClipboardIsRestoredEmpty() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()

        let snapshot = ClipboardSnapshot.capture(from: pasteboard)
        #expect(snapshot.items.isEmpty)
        #expect(snapshot.droppedItems == 0)
        let ourChangeCount = ClipboardSnapshot.write("transcript", to: pasteboard)
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == nil)
    }

    // MARK: The transcript as a promise

    /// Main actor: AppKit serves an in-process promise read synchronously and
    /// warns when that happens off the main thread.
    @MainActor @Test func publishedTranscriptIsServedMarkedAndReportsTheRead() throws {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        let reads = Recorder<ContinuousClock.Instant>()
        let promise = TranscriptPromise("hello") { _, instant in reads.append(instant) }

        let changeCount = ClipboardSnapshot.publish(promise, to: pasteboard)

        #expect(changeCount == pasteboard.changeCount)
        #expect(reads.all.count == 0)
        let types = Set(try #require(pasteboard.pasteboardItems?.first).types)
        #expect(types.isSuperset(of: [.string, Self.transient, Self.concealed, Self.autoGenerated, Self.source]))
        #expect(pasteboard.string(forType: .string) == "hello")
        #expect(reads.all.count == 1)
    }

    @MainActor @Test func restoreRoundTripsAfterAPublishedTranscript() {
        let pasteboard = Self.namedPasteboard()
        defer { pasteboard.releaseGlobally() }
        pasteboard.clearContents()
        pasteboard.setString("user text", forType: .string)
        let snapshot = ClipboardSnapshot.capture(from: pasteboard)

        let promise = TranscriptPromise("transcript") { _, _ in }
        let ourChangeCount = ClipboardSnapshot.publish(promise, to: pasteboard)
        #expect(pasteboard.string(forType: .string) == "transcript")
        snapshot.restore(ifChangeCountIs: ourChangeCount, on: pasteboard)

        #expect(pasteboard.string(forType: .string) == "user text")
    }

    // MARK: When the old clipboard comes back

    private static let posted = ContinuousClock.now
    private static func due(read: Duration?) -> Duration {
        ClipboardKeeper.restoreDue(
            posted: posted, lastRead: read.map { posted + $0 },
            floor: .milliseconds(400), settle: .milliseconds(200), cap: .seconds(8)) - posted
    }

    @Test func nothingReadWaitsForTheCap() {
        #expect(Self.due(read: nil) == .seconds(8))
    }

    @Test func aPromptReadKeepsTheOldDelay() {
        #expect(Self.due(read: .milliseconds(12)) == .milliseconds(400))
    }

    @Test func aLateReadIsWaitedFor() {
        // A busy page reads a second after Cmd+V; the old 400 ms delay alone
        // had already put the user's clipboard back by then.
        #expect(Self.due(read: .milliseconds(1_006)) == .milliseconds(1_206))
    }

    @Test func aReadNearTheCapStillEndsAtTheCap() {
        #expect(Self.due(read: .milliseconds(7_900)) == .seconds(8))
    }

    @Test func aReadBeforeCmdVKeepsTheOldDelay() {
        #expect(Self.due(read: .milliseconds(-5)) == .milliseconds(400))
    }
}
