import AppKit
import Foundation
import os

/// Every item on the pasteboard with every representation, so images, rich
/// text and file promises survive the round trip. Data is value type only,
/// which keeps the snapshot `Sendable` across the restore delay.
struct ClipboardSnapshot: Sendable {
    var items: [[String: Data]]
    /// Items left out for being larger than the capture's limit. A snapshot
    /// with any is incomplete, and one with nothing else is no snapshot at
    /// all: restoring it would wipe the clipboard.
    var droppedItems = 0

    /// The nspasteboard.org marker types. Maccy, Paste, Raycast and the rest
    /// skip an item carrying these instead of recording it: transient means
    /// "do not keep", concealed means "this is secret-ish", auto-generated
    /// means "no human copied this". All three go on every transcript,
    /// including the clipboard-only path without Accessibility, where the
    /// user presses ⌘V themselves — a manager that recorded it there would
    /// be just as much of a leak.
    static let markerTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Who wrote it, for managers that show or filter by source.
    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Items up to this size are kept; a larger one is left out of the
    /// snapshot, so it is not restored. The capture runs at key-down, off the
    /// release-to-paste path, so this does not bound the paste; it bounds the
    /// memory a snapshot holds for up to `restoreCap`. A copied video or a
    /// huge image is the case: losing that from the clipboard is the price
    /// of not holding hundreds of megabytes for every dictation.
    static let maximumItemBytes = 64 * 1024 * 1024

    private static let log = Logger(subsystem: "de.dinooo13.pladder", category: "paste")

    static func capture(from pasteboard: NSPasteboard, maximumItemBytes: Int = maximumItemBytes) -> Self {
        var dropped = 0
        let items = (pasteboard.pasteboardItems ?? []).compactMap { item -> [String: Data]? in
            var representations: [String: Data] = [:]
            var total = 0
            for type in item.types {
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                guard total <= maximumItemBytes else {
                    dropped += 1
                    return nil
                }
                representations[type.rawValue] = data
            }
            return representations.isEmpty ? nil : representations
        }
        if dropped > 0 {
            log.notice("clipboard snapshot incomplete: \(dropped) of \(dropped + items.count) items over \(maximumItemBytes / 1_048_576) MB left out")
        }
        return Self(items: items, droppedItems: dropped)
    }

    /// Replaces the pasteboard with `text`, marked as a transcript nobody
    /// should archive, and returns the resulting change count so we can tell
    /// later whether anybody else has written since. For the clipboard-only
    /// path, where the transcript is the result and stays.
    ///
    /// One item carrying five types, so it is still a single write: the
    /// markers cost a few bytes of IPC, not a second round trip.
    static func write(_ text: String, to pasteboard: NSPasteboard) -> Int {
        let item = markedItem()
        item.setString(text, forType: .string)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    /// `write`, with the text served by `promise` when an app reads it, so
    /// the read is reported. Still a single write.
    ///
    /// The markers matter twice here. Something in macOS reads every
    /// unmarked write about 15 ms after it lands, paste or no paste
    /// (Universal Clipboard, by the log); with the markers it does not.
    /// Without them that read would count as the paste and bring the old
    /// clipboard back before the target app had read the transcript.
    static func publish(_ promise: TranscriptPromise, to pasteboard: NSPasteboard) -> Int {
        let item = markedItem()
        item.setDataProvider(promise, forTypes: [.string])
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    private static func markedItem() -> NSPasteboardItem {
        let item = NSPasteboardItem()
        for type in markerTypes { item.setData(Data(), forType: type) }
        // `Bundle.main.bundleIdentifier` is nil for the bare SwiftPM binary
        // and is the harness's id under `swift test`; the app's own id is
        // the fallback.
        item.setString(Bundle.main.bundleIdentifier ?? "de.dinooo13.pladder", forType: sourceType)
        return item
    }

    /// Puts the snapshot back, unless the user copied something else while we
    /// were pasting; their copy wins in that case.
    ///
    /// A snapshot whose every item was too large to keep is not restored:
    /// clearing would leave the user with an empty clipboard, and the
    /// transcript, text they have just said, is the lesser loss. An empty
    /// snapshot of an empty clipboard is restored, to empty.
    func restore(ifChangeCountIs expected: Int, on pasteboard: NSPasteboard) {
        guard pasteboard.changeCount == expected else { return }
        guard !items.isEmpty || droppedItems == 0 else {
            Self.log.notice("clipboard not restored: every item was too large to keep; the transcript stays")
            return
        }
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

/// The transcript as a pasteboard promise: the text is handed over when an app
/// asks for it, and every ask is reported, which is how `ClipboardKeeper`
/// knows the paste happened.
///
/// AppKit calls the provider on the main thread, so an app reading the
/// transcript waits for Pladder's main thread to be free. The time from Cmd+V
/// to the first read is logged for that reason.
final class TranscriptPromise: NSObject, NSPasteboardItemDataProvider, Sendable {
    let text: String
    private let now: @Sendable () -> ContinuousClock.Instant
    private let onRead: @Sendable (TranscriptPromise, ContinuousClock.Instant) -> Void

    init(
        _ text: String,
        now: @escaping @Sendable () -> ContinuousClock.Instant = { .now },
        onRead: @escaping @Sendable (TranscriptPromise, ContinuousClock.Instant) -> Void
    ) {
        self.text = text
        self.now = now
        self.onRead = onRead
    }

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        item.setString(text, forType: type)
        onRead(self, now())
    }

    func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}
