import AppKit
import Foundation
import os

struct ClipboardSnapshot: Sendable {
    var items: [[String: Data]]
    var droppedItems = 0

    // nspasteboard.org markers: clipboard managers (Maccy, Paste, Raycast) skip an item
    // carrying them. On every transcript, the clipboard-only path included.
    static let markerTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    // Bounds the memory a snapshot holds for up to `restoreCap`; a larger item, a copied
    // video say, is left out and not restored.
    static let maximumItemBytes = 64 * 1024 * 1024

    private static let log = Logger(subsystem: "de.dinooo13.pladder", category: "paste")

    static func capture(from pasteboard: NSPasteboard, maximumItemBytes: Int = maximumItemBytes) -> Self {
        var dropped = 0
        let items = (pasteboard.pasteboardItems ?? []).compactMap { item -> [String: Data]? in
            var representations: [String: Data] = [:]
            var total = 0
            for type in item.types {
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                guard total <= maximumItemBytes else {
                    dropped += 1
                    return nil
                }
                representations[type.rawValue] = data
            }
            return representations.isEmpty ? nil : representations
        }
        if dropped > 0 {
            log.notice("clipboard snapshot incomplete: \(dropped) of \(dropped + items.count) items over \(maximumItemBytes / 1_048_576) MB left out")
        }
        return Self(items: items, droppedItems: dropped)
    }

    static func write(_ text: String, to pasteboard: NSPasteboard) -> Int {
        let item = markedItem()
        item.setString(text, forType: .string)
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    // The markers matter twice here: something in macOS (Universal Clipboard, by the
    // log) reads every unmarked write about 15 ms after it lands, and that read would
    // pass for the paste and bring the old clipboard back too early.
    static func publish(_ promise: TranscriptPromise, to pasteboard: NSPasteboard) -> Int {
        let item = markedItem()
        item.setDataProvider(promise, forTypes: [.string])
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    private static func markedItem() -> NSPasteboardItem {
        let item = NSPasteboardItem()
        for type in markerTypes { item.setData(Data(), forType: type) }
        // Nil for the bare SwiftPM binary, the harness's id under `swift test`.
        item.setString(Bundle.main.bundleIdentifier ?? "de.dinooo13.pladder", forType: sourceType)
        return item
    }

    // A snapshot whose every item was too large is not restored: clearing would leave
    // an empty clipboard, and the transcript is the lesser loss.
    func restore(ifChangeCountIs expected: Int, on pasteboard: NSPasteboard) {
        guard pasteboard.changeCount == expected else { return }
        guard !items.isEmpty || droppedItems == 0 else {
            Self.log.notice("clipboard not restored: every item was too large to keep; the transcript stays")
            return
        }
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        let restored = items.map { representations -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        pasteboard.writeObjects(restored)
    }
}

// AppKit calls the provider on the main thread, so an app reading the transcript
// waits for Pladder's main thread; the first read's delay is logged for that.
final class TranscriptPromise: NSObject, NSPasteboardItemDataProvider, Sendable {
    let text: String
    private let now: @Sendable () -> ContinuousClock.Instant
    private let onRead: @Sendable (TranscriptPromise, ContinuousClock.Instant) -> Void

    init(
        _ text: String,
        now: @escaping @Sendable () -> ContinuousClock.Instant = { .now },
        onRead: @escaping @Sendable (TranscriptPromise, ContinuousClock.Instant) -> Void
    ) {
        self.text = text
        self.now = now
        self.onRead = onRead
    }

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        item.setString(text, forType: type)
        onRead(self, now())
    }

    func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}
